"""Shared physics unit conversion table.

Scale convention: SI value = raw value * scale.
"""

from __future__ import annotations

UNIT_TO_SI: dict[str, tuple[float, str]] = {
    "": (1.0, ""),
    "dimensionless": (1.0, "dimensionless"),
    "%": (0.01, "dimensionless"),
    "m": (1.0, "m"),
    "cm": (1e-2, "m"),
    "mm": (1e-3, "m"),
    "km": (1e3, "m"),
    "m²": (1.0, "m2"),
    "m2": (1.0, "m2"),
    "cm²": (1e-4, "m2"),
    "cm2": (1e-4, "m2"),
    "mm²": (1e-6, "m2"),
    "mm2": (1e-6, "m2"),
    "s": (1.0, "s"),
    "ms": (1e-3, "s"),
    "us": (1e-6, "s"),
    "μs": (1e-6, "s"),
    "hz": (1.0, "Hz"),
    "khz": (1e3, "Hz"),
    "mhz": (1e6, "Hz"),
    "ghz": (1e9, "Hz"),
    "rad/s": (1.0, "rad/s"),
    "v": (1.0, "V"),
    "mv": (1e-3, "V"),
    "uv": (1e-6, "V"),
    "μv": (1e-6, "V"),
    "kv": (1e3, "V"),
    "a": (1.0, "A"),
    "ma": (1e-3, "A"),
    "ua": (1e-6, "A"),
    "μa": (1e-6, "A"),
    "c": (1.0, "C"),
    "mc": (1e-3, "C"),
    "uc": (1e-6, "C"),
    "μc": (1e-6, "C"),
    "nc": (1e-9, "C"),
    "pc": (1e-12, "C"),
    "f": (1.0, "F"),
    "mf": (1e-3, "F"),
    "microf": (1e-6, "F"),
    "uf": (1e-6, "F"),
    "μf": (1e-6, "F"),
    "nf": (1e-9, "F"),
    "pf": (1e-12, "F"),
    "h": (1.0, "H"),
    "mh": (1e-3, "H"),
    "microh": (1e-6, "H"),
    "uh": (1e-6, "H"),
    "μh": (1e-6, "H"),
    "ohm": (1.0, "Ohm"),
    "Ω": (1.0, "Ohm"),
    "kohm": (1e3, "Ohm"),
    "kΩ": (1e3, "Ohm"),
    "mohm": (1e-3, "Ohm"),
    "mΩ": (1e-3, "Ohm"),
    "megohm": (1e6, "Ohm"),
    "n": (1.0, "N"),
    "mn": (1e-3, "N"),
    "j": (1.0, "J"),
    "mj": (1e-3, "J"),
    "uj": (1e-6, "J"),
    "μj": (1e-6, "J"),
    "w": (1.0, "W"),
    "mw": (1e-3, "W"),
    "kw": (1e3, "W"),
    "t": (1.0, "T"),
    "mt": (1e-3, "T"),
    "wb": (1.0, "Wb"),
    "mwb": (1e-3, "Wb"),
    "uwb": (1e-6, "Wb"),
    "μwb": (1e-6, "Wb"),
    "n/c": (1.0, "N/C"),
    "v/m": (1.0, "V/m"),
}
